services:
  count-mcp-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: count_mcp_server
    ports:
      - "8000:8000"
    restart: unless-stopped

  count-mcp-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: count_mcp_client
    env_file:
      - .env
    environment:
      - MCP_URL=${MCP_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FASTMCP_API_KEY=${FASTMCP_API_KEY}
    command: ["python", "count_r_client.py"]
    depends_on:
      count-mcp-server:
        condition: service_started
    restart: "no"
